<?php
/**
 * @var Modules\Button\Block\BlockButton $block
 */

?>

<?php if ($block->popupEnabled()): ?>
    <div id="custom-popup-modal">

    </div>

    <button id="click-me">Popup button</button>
    <script>
        require(
            [
                'jquery',
                'Magento_Ui/js/modal/modal'
            ],
            function(
                $,
                modal
            ) {
                let title = '<?php echo $block->getTitle() ?>';
                var options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    title : title,
                    modalClass: 'custom-popup-modal',
                    buttons: [{
                        text: $.mage.__('Close'),
                        class: '',
                        click: function () {
                            this.closeModal();
                        }
                    }]
                };

                var popup = modal(options, $('#custom-popup-modal'));
                $("#click-me").on('click',function(){
                        $("#custom-popup-modal").modal("openModal");
                    });
            }
        );
    </script>
<?php endif; ?>


